# Generated by Django 3.1.7 on 2021-07-13 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_regiona', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Raion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_raiona', models.IntegerField(unique=True)),
                ('raion', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klassifikator.region')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
    ]
