# Generated by Django 3.1.7 on 2021-07-13 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='otdel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование отдела'),
        ),
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 9, 24, 48, 126300), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 9, 24, 48, 126300), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
