# Generated by Django 3.1.7 on 2021-07-13 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_auto_20210713_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats_ulus',
            name='ulus_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование улуса'),
        ),
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 12, 38, 58, 885175), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 12, 38, 58, 885175), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='stats_ulus',
            name='ulus',
            field=models.CharField(max_length=10, verbose_name='улус'),
        ),
    ]
