# Generated by Django 3.2 on 2021-07-13 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0003_auto_20210713_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 6, 16, 23, 276775), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 6, 16, 23, 276775), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
