# Generated by Django 3.2.7 on 2021-09-06 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0007_auto_20210906_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 3, 41, 23, 869168), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 3, 41, 23, 868423), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
