# Generated by Django 3.2.7 on 2021-09-06 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0008_auto_20210906_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 5, 34, 13, 897435), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 5, 34, 13, 896591), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
