# Generated by Django 3.2.7 on 2021-09-06 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0009_auto_20210906_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 5, 35, 44, 369036), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 6, 5, 35, 44, 368342), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
