# Generated by Django 3.2.7 on 2021-12-16 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0012_auto_20211216_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 9, 33, 681255), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 9, 33, 680608), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
