# Generated by Django 3.2.7 on 2021-12-16 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0013_auto_20211216_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 11, 25, 222207), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 11, 25, 221418), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
