# Generated by Django 3.2.7 on 2021-12-16 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0014_auto_20211216_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 15, 40, 364517), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 16, 5, 15, 40, 363839), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
