# Generated by Django 3.2.7 on 2021-12-17 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0016_auto_20211216_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 17, 3, 21, 23, 908903), max_length=50, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='add_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 17, 3, 21, 23, 908117), max_length=50, verbose_name='Дата добавления'),
        ),
    ]
